version: "3"
services:
  site1:
    image: babujii/site1:latest
    container_name: site1
    restart: always

  site2:
    image: babujii/site2:latest
    container_name: site2
    restart: always

  reverse-proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - site1
      - site2

